version: "3.8"

services:
  django:
    build: .
    container_name: "django_lr_server"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=admin # TODO: REMOVE
      - DJANGO_SUPERUSER_PASSWORD=admin # TODO: REMOVE
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command:
      [
        "/app/entrypoint.sh",
        "celery",
        "-A",
        "lr_server",
        "worker",
        "--loglevel=info",
      ]
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command:
      [
        "/app/entrypoint.sh",
        "celery",
        "-A",
        "lr_server",
        "beat",
        "--loglevel=info",
      ]
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis
